### ISSUE TITLE
'Every' in examples is misleading

### ISSUE THREAD

**Issue by udhos** [qvl/sleepto#12]
I guess the 'every' word makes sense when sleepto is called in a recurrent context.

However it seems misleading as is:

      # Every 10th of month at 3pm
      sleepto -day 10 -hour 15 /bin/send-report
      # Every 15 minutes
      sleepto -minute 0,15,30,45 say "Hello human"
      # Every day at 1am
      sleepto -hour 1 && ~/dbbackup.sh

How about replacing it with a more accurate description?

      # Next 10th of month at 3pm
      sleepto -day 10 -hour 15 /bin/send-report
      # Next occurence of one quarter of hour
      sleepto -minute 0,15,30,45 say "Hello human"
      # Next day at 1am
      sleepto -hour 1 && ~/dbbackup.sh

**Comment by jorinvo** [comment]
Thank you @udhos! Was too focused on my personal use cases when phrasing these comments.
I used your suggestions here: https://github.com/qvl/sleepto/commit/5f6b10762367c9394deeddb527d0332ee2e926ee
